# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectIGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QFileDialog
from mainSecondWindow import MainSecondWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 787)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.949, x2:1, y2:0, stop:0.0995025 rgba(82, 120, 145, 255), stop:0.985075 rgba(61, 71, 91, 255));\n"
"border-radius: 20px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Title_Bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Title_Bar.setStyleSheet("background-color: none")
        self.Title_Bar.setFrameShape(QtWidgets.QFrame.Box)
        self.Title_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_Bar.setObjectName("Title_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Title_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.Title_Bar)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("color: rgb(177, 197, 212);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.Title_Bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setGeometry(QtCore.QRect(10, 20, 16, 16))
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(85, 255, 127, 150);\n"
"\n"
"}\n"
"")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 0, 0, 150);\n"
"\n"
"}\n"
"")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setGeometry(QtCore.QRect(40, 20, 16, 16))
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 170, 0, 150);\n"
"\n"
"}\n"
"")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout_2.addWidget(self.Title_Bar)
        self.Content_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Content_Bar.setStyleSheet("")
        self.Content_Bar.setFrameShape(QtWidgets.QFrame.Panel)
        self.Content_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content_Bar.setObjectName("Content_Bar")
        self.frame = QtWidgets.QFrame(self.Content_Bar)
        self.frame.setGeometry(QtCore.QRect(40, 30, 911, 641))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 70, 891, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"color: rgb(216, 185, 170);\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_predict = QtWidgets.QPushButton(self.frame)
        self.btn_predict.setGeometry(QtCore.QRect(510, 380, 150, 75))
        self.btn_predict.setMinimumSize(QtCore.QSize(150, 75))
        self.btn_predict.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.btn_predict.setFont(font)
        self.btn_predict.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.btn_predict.setObjectName("btn_predict")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 250, 711, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(186, 207, 222);\n"
"background-color: rgb(158, 176, 189);\n"
"color: rgb(213, 238, 255);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"QLineEdit:hover {\n"
" border: 2px solid rgb(213, 238, 255);\n"
"}\n"
"QLineEdit:focus{\n"
" border: 2px solid rgb(213, 238, 255);\n"
"background-color: rgb(158, 176, 189);\n"
"}\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.btn_uploadimg = QtWidgets.QPushButton(self.frame)
        self.btn_uploadimg.setGeometry(QtCore.QRect(240, 380, 150, 75))
        self.btn_uploadimg.setMinimumSize(QtCore.QSize(150, 75))
        self.btn_uploadimg.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.btn_uploadimg.setFont(font)
        self.btn_uploadimg.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.btn_uploadimg.setObjectName("btn_uploadimg")
        self.verticalLayout_2.addWidget(self.Content_Bar)
        self.Credits_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Credits_Bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Credits_Bar.setStyleSheet("background-color: none")
        self.Credits_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Credits_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Credits_Bar.setObjectName("Credits_Bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Credits_Bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.Credits_Bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        self.label_credits.setGeometry(QtCore.QRect(20, 0, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(177, 197, 212);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.frame_grip = QtWidgets.QFrame(self.Credits_Bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout_2.addWidget(self.Credits_Bar)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Non-Parametric Classifier"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.label.setText(_translate("MainWindow", "Welcome to the non-parametric age classifier!"))
        self.btn_predict.setText(_translate("MainWindow", "Predict"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter an image location..."))
        self.btn_uploadimg.setText(_translate("MainWindow", "Upload Image"))
        self.label_credits.setText(_translate("MainWindow", "By : Rachelle Abdel Massih, Myriam Abou Atmeh, Sara Oud"))
    #Connect the 'Upload Image' button to the btn_oploadimg_handler function
        self.btn_uploadimg.clicked.connect(self.btn_uploadimg_handler)
    #Connect the 'Predict' button to the openWindow function that opens the second window of the GUI
        self.btn_predict.clicked.connect(self.openWindow)


    def btn_uploadimg_handler(self):
        # print("Button pressed")
    #Call the open_dialog_box function
        self.open_dialog_box()

    def open_dialog_box(self):
    #Open the file explorer on local disk and get the path of the selected image
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        print(path)
    #Display the selected path on the QLineEdit widget
        self.lineEdit.setText(str(path))

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = MainSecondWindow()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
