# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(1007, 790)
        SecondWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.949, x2:1, y2:0, stop:0.0995025 rgba(82, 120, 145, 255), stop:0.985075 rgba(61, 71, 91, 255));\n"
"border-radius: 20px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Title_Bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Title_Bar.setStyleSheet("background-color: none")
        self.Title_Bar.setFrameShape(QtWidgets.QFrame.Box)
        self.Title_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_Bar.setObjectName("Title_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Title_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.Title_Bar)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("color: rgb(177, 197, 212);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.Title_Bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setGeometry(QtCore.QRect(10, 20, 16, 16))
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(85, 255, 127, 150);\n"
"\n"
"}\n"
"")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 0, 0, 150);\n"
"\n"
"}\n"
"")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setGeometry(QtCore.QRect(40, 20, 16, 16))
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 170, 0, 150);\n"
"\n"
"}\n"
"")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout_2.addWidget(self.Title_Bar)
        self.Content_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Content_Bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Content_Bar.setStyleSheet("")
        self.Content_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content_Bar.setObjectName("Content_Bar")
        self.frame = QtWidgets.QFrame(self.Content_Bar)
        self.frame.setGeometry(QtCore.QRect(20, 0, 941, 681))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.EdgeImg_label = QtWidgets.QLabel(self.frame)
        self.EdgeImg_label.setGeometry(QtCore.QRect(520, 40, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.EdgeImg_label.setFont(font)
        self.EdgeImg_label.setStyleSheet("background-color: rgb(104, 101, 115);\n"
"border: 2px solid rgb(177, 197, 212);\n"
"color: rgb(177, 197, 212);")
        self.EdgeImg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeImg_label.setObjectName("EdgeImg_label")
        self.InputImg_label = QtWidgets.QLabel(self.frame)
        self.InputImg_label.setGeometry(QtCore.QRect(50, 40, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.InputImg_label.setFont(font)
        self.InputImg_label.setStyleSheet("background-color: rgb(104, 101, 115);\n"
"border: 2px solid rgb(177, 197, 212);\n"
"color: rgb(177, 197, 212);")
        self.InputImg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.InputImg_label.setObjectName("InputImg_label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 440, 521, 261))
        self.frame_2.setStyleSheet("background-color: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Prediction_label = QtWidgets.QLabel(self.frame_2)
        self.Prediction_label.setGeometry(QtCore.QRect(20, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.Prediction_label.setFont(font)
        self.Prediction_label.setStyleSheet("color: rgb(216, 185, 170);")
        self.Prediction_label.setObjectName("Prediction_label")
        self.accuracy_label = QtWidgets.QLabel(self.frame_2)
        self.accuracy_label.setGeometry(QtCore.QRect(20, 170, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.accuracy_label.setFont(font)
        self.accuracy_label.setStyleSheet("color: rgb(213, 184, 169);")
        self.accuracy_label.setObjectName("accuracy_label")
        self.results_label = QtWidgets.QLabel(self.frame_2)
        self.results_label.setGeometry(QtCore.QRect(10, 5, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.results_label.setFont(font)
        self.results_label.setStyleSheet("color: rgb(216, 185, 170);\n"
"border: 5px solid rgb(216, 185, 170);")
        self.results_label.setObjectName("results_label")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(110, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(216, 185, 170);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(170, 170, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 100, 381, 311))
        self.label_5.setStyleSheet("background-color: none;\n"
"border: none;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(510, 100, 381, 311))
        self.label_6.setStyleSheet("background-color: none;\n"
"border: none;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.Content_Bar)
        self.Credits_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Credits_Bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Credits_Bar.setStyleSheet("background-color: none")
        self.Credits_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Credits_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Credits_Bar.setObjectName("Credits_Bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Credits_Bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.Credits_Bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        self.label_credits.setGeometry(QtCore.QRect(20, 0, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(177, 197, 212);\n"
"")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.frame_grip = QtWidgets.QFrame(self.Credits_Bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout_2.addWidget(self.Credits_Bar)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        SecondWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "SecondWindow"))
        self.label_title.setText(_translate("SecondWindow", "Non-Parametric Classifier"))
        self.EdgeImg_label.setText(_translate("SecondWindow", "Edge-Detected Image:"))
        self.InputImg_label.setText(_translate("SecondWindow", "Input Image:"))
        self.Prediction_label.setText(_translate("SecondWindow", "Prediction :"))
        self.accuracy_label.setText(_translate("SecondWindow", "Prediction Accuracy :"))
        self.results_label.setText(_translate("SecondWindow", "Classifier Results :"))
        self.label_credits.setText(_translate("SecondWindow", "By : Rachelle Abdel Massih, Myriam Abou Atmeh, Sara Oud"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
